---
version: "3.8"


services:

  db:
    image: postgres:13-alpine
    init: true
    restart: always
    networks:
      - dev
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    tmpfs: /var/lib/postgresql/data

  assets:
    image: go-cloud-run:assets
    build:
      context: ./js
      dockerfile: Dockerfile-dev
    volumes:
      - ./js:/app:cached
      - assets:/app/dist
    restart: on-failure

  server:
    image: go-cloud-run:dev
    build:
      context: ./go
      dockerfile: Dockerfile-dev
    networks:
      - dev
    ports:
      - 8080:8080
    volumes:
      - ./go:/app:cached
      - assets:/assets:cached
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - SERVER_MODE=development
      - ASSETS_PATH=/assets
      - DATABASE_URL=
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    restart: on-failure

networks:
  dev:
    name: go-cloud-run

volumes:
  assets:
    name: go-cloud-run-assets
