FROM golang:1.15-buster

RUN go get github.com/silenceper/gowatch      && \
    ln -s /go/bin/gowatch /bin

WORKDIR /app

COPY ./go.mod  .
COPY ./go.sum  .

RUN go mod download

COPY .  .

CMD ["gowatch"]
